[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", 
    "@openzeppelin/contracts-upgrade/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/", 
    "@aave-coreV3/contracts/=lib/aave-v3-core/contracts/", 
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts",
    "@uniswap/v2-core/contracts/=lib/v2-core/contracts"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
